name: Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run docs:build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PHOENIX_SYNC_TOKEN }}
          publish_dir: docs/.vitepress/dist


      - name: Deploy to Aliyun OSS
        uses: fangbinwei/aliyun-oss-website-action@v1
        with:
          accessKeyId: ${{ secrets.OSS_ACCESS_KEY_ID }}
          accessKeySecret: ${{ secrets.OSS_SECRET_ACCESS_KEY }}
          bucket: ${{ secrets.OSS_BUCKET }}
          # use your own endpoint
          endpoint: oss-cn-guangzhou.aliyuncs.com
          folder: docs/.vitepress/dist

          
