name: Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run docs:build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PHOENIX_SYNC_TOKEN }}
          publish_dir: docs/.vitepress/dist


      - name: Deploy to Aliyun OSS
        uses: jakejarvis/s3-sync-action@master
        with:
          args:  --follow-symlinks --delete # --acl public-read
        env:
          AWS_S3_BUCKET: ${{ secrets.OSS_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.OSS_SECRET_ACCESS_KEY }}
          AWS_S3_ENDPOINT: ${{ secrets.OSS_ENDPOINT }}
          SOURCE_DIR: docs/.vitepress/dist      # optional: defaults to entire repository
